#pragma checksum "C:\Users\jre06\source\repos\TCSS_WindowsApp\TCSS_WindowsApp\App.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "250EDEECD43E739AFEB051362828C286"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSS_WindowsApp
{
    partial class App : global::Windows.UI.Xaml.Application
    {
    }
}

